image: node:20-alpine

stages:
  - test

api-automation-test:
  stage: test
  before_script:
    - npm install -g newman newman-reporter-allure
    - npm install
  script:
    - |
      newman run api-automation/collections/auth/auth.dummyjson.postman_collection.json \
        --folder "Positive Flow" \
        -e api-automation/environments/prod/prod.postman_environment.json \
        --env-var "username=$API_USERNAME" \
        --env-var "password=$API_PASSWORD" \
        -r allure,cli
    - |
      newman run api-automation/collections/auth/auth.dummyjson.postman_collection.json \
        --folder "Negative Flow" \
        -e api-automation/environments/prod/prod.postman_environment.json \
        --env-var "username=$API_USERNAME" \
        --env-var "password=$API_PASSWORD" \
        -r allure,cli
  artifacts:
    paths:
      - allure-results/
    expire_in: 30 days
