name: API Automation Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Newman & Allure Reporter
        run: npm install -g newman newman-reporter-allure

      - name: Run Positive Tests
        continue-on-error: true
        run: |
          newman run api-automation/collections/auth/auth.dummyjson.postman_collection.json \
            -e api-automation/environments/prod/prod.postman_environment.json \
            --folder "Positive Flow" \
            -r allure,cli

      - name: Run Negative Tests
        continue-on-error: true
        run: |
          newman run api-automation/collections/auth/auth.dummyjson.postman_collection.json \
            -e api-automation/environments/prod/prod.postman_environment.json \
            --folder "Negative Flow" \
            -r allure,cli

      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --output allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
